[project]
name = "bridgic-examples"
version = "0.1.0"
description = "Example code using the Bridgic framework."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bridgic>=0.1.1",
    "bridgic-llms-openai>=0.1.1",
]
